#! /bin/bash -e
# myvcs
myname="${0##*/} (PID $$)"
. /.fetch4merc 
STARTARG=0
REFEXISTS=0
declare -a ARRAY
declare -a DaemonARRAY

if [ "$1" = "-w" ]; then
	QQEDIR=$2
	STARTARG=2
	if [ "$2" = "-r" ]; then
		echo "Incorrect request fetch4me -w -r." 1>&2
		exit 1
	fi
	
	if [ "$2" = "-w" ]; then
		echo "Incorrect request fetch4me -w -w." 1>&2
		exit 1
	fi
	
	if [ "$3" = "-r" ]; then
		REFERRER=$4
		REFEXISTS=1
		STARTARG=4
	fi
 elif [ "$1" = "-r" ]; then
	REFERRER=$2
	REFEXISTS=1
	STARTARG=2	
	if [ "$2" = "-w" ]; then
		echo "Incorrect request fetch4me -r -w." 1>&2
		exit 1
	fi
	
	if [ "$2" = "-r" ]; then		
		echo "Incorrect request fetch4me -r -r." 1>&2
		exit 1
	fi
		
	if [ $# -le "2" ]; then
		echo "Incorrect request. No URLs." 1>&2
		exit 1
	fi
	
	if [ $3 = "-w" ]; then
		QQEDIR=$4
		STARTARG=4
	fi
fi
 	
if [ -z "$QQEDIR" ]; then
	QQEDIR="/.fetch4me"
fi

if [ -z "$GETELEMFUNC" ]; then
	GETELEMFUNC="wget"
fi

if [ $# -le "2" -a "$REFEXISTS" = "1" ]; then
	echo "Incorrect request. No URLs." 1>&2
	exit 1
fi


ARGS=("$@")
if [[ -f $QQEDIR/RequestsNum ]];then
	read rqstNum < $QQEDIR/RequestsNum	
else
	rqstNum=0
fi

urlNum=0
if [[ ! -d $QQEDIR ]];then 
	mkdir $QQEDIR
fi

for (( i=$STARTARG; i<${#ARGS[@]}; i++)); do
	if [ "${ARGS[${i}]}" = "-w" ]; then	
		echo "Incorrect request. -w in a wrong place." 1>&2
		exit 1
	fi	
		
	if [ "${ARGS[${i}]}" = "-r" ]; then
		echo "Incorrect request. -r in a wrong place." 1>&2
		exit 1
	fi
	((rqstNum=$rqstNum+1))
	((urlNum=$urlNum+1))
	ARRAY[$urlNum]=${ARGS[${i}]}
	
done


if [  -f $QQEDIR/Daemon ];then 
	if [ $urlNum > 0 ];then
		for (( i=1;i<=$urlNum;i++ )); do
			echo $(($rqstNum-$urlNum+$i)) >"$QQEDIR/RequestsNum"	
			echo $REFERRER > "$QQEDIR/REFERRER$(($rqstNum-$urlNum+$i))"
			echo ${ARRAY[${i}]} > "$QQEDIR/URL$(($rqstNum-$urlNum+$i))"		
		done
	else
		echo "No URLs" 1>&2
	fi	

else

	for (( i=1;i<=$urlNum;i++ )); do
		echo $(($rqstNum-$urlNum+$i)) >"$QQEDIR/RequestsNum"	
		echo $REFERRER > "$QQEDIR/REFERRER$(($rqstNum-$urlNum+$i))"
		echo ${ARRAY[${i}]} > "$QQEDIR/URL$(($rqstNum-$urlNum+$i))"		
	done


#trap 'exit 0' HUP  #On SIGHUP , re-read $config

# ENDLESS loop until killer by signal 15 :
exec >/dev/null
exec < /dev/null
1>&2
(
trap "" SIGHUP

while :
do
#touch $QQEDIR/Daemon
#write PID make!
if [ ! -f $QQEDIR/RequestsNum ] ;then
	echo "Error deleting files" 1&>2
	s=0
	echo $s >"$QQEDIR/RequestsNum"	
	fi


	read s < $QQEDIR/RequestsNum	
	echo "s=$s"

	if [ ! $s = 0 ];then
		for (( i=0;i<=$((s-1));i++ )); do
			read temp < $QQEDIR/REFERRER$((i+1))
			read temp1 < $QQEDIR/URL$((i+1))
			rm $QQEDIR/REFERRER$((i+1))
			rm $QQEDIR/URL$((i+1))	
			DaemonARRAY=( "${DaemonARRAY[@]}" "$temp" ) # Mbe not working
			DaemonARRAY=( "${DaemonARRAY[@]}" "$temp1" ) # Mbe not working
			echo "DaemonArray $((i*2)) = ${DaemonARRAY[$((2*i))]}"
			echo "DaemonArray $((2*i+1)) = ${DaemonARRAY[$((2*i+1))]}"
		done
		echo 0 > "$QQEDIR/RequestsNum"	
	fi
	
 if [ ! ${DaemonARRAY[1]} = "" ];then

echo "Downloading now- Referrer-${DaemonARRAY[0]} Url-${DaemonARRAY[1]} " >>$QUEUE/.status
echo "Downloading queue:" >>$QUEUE/.status
for (( i=2;i<${#DaemonARRAY[@]};i++ ));do
echo "${DaemonARRAY[${i}]}" >>$QUEUE/.status
done
for (( i=2;i<${#DaemonARRAY[@]};i++ ));do
echo "${DaemonARRAY[${i}]}" >>$QUEUE/.queue
done
`$GETELEMFUNC -q -P "/Downloads/fetched4you/${DaemonARRAY[0]}/${DaemonARRAY[1]}" ${DaemonARRAY[1]}`
	
	echo "`date +%s` ${DaemonARRAY[0]} ${DaemonARRAY[1]}" >>$QQEDIR/.finished 

	temp3=${#DaemonARRAY[@]} 
	((temp3=temp3-1))
	echo "temp3=$temp3"
	declare -a DaemonARRAYNEW=( ${DaemonARRAY[@]:2:$temp3} )
	declare -a DaemonARRAY=( ${DaemonARRAYNEW[@]:0:$temp3} )
	echo "DaemonARRAY=${DaemonARRAY[@]}"
	echo "DaemonARRAYNEW=${DaemonARRAYNEW[@]}"
	
	echo 0 > "$QQEDIR/RequestsNum"	
	fi

touch $QQEDIR/.finished
prov= stat --format %Z $QQEDIR/.finished
echo $prov	   
	
sleep 3
done
) &
fi



