#! /bin/bash -e
# myvcs
. /.fetch4merc 
STARTARG=0
REFEXISTS=0
declare -a ARRAY
declare -a DaemonArray
declare -a array1
killed=0

Hype()
{
	local -a TMP
	local -a hype
	$($CopyArray $1 TMP)
	TMP=( ${TMP[@]} ${hype[@]} )
	$($CopyArray TMP $2)

}

startDaemon () {
	exec >/dev/null
	exec < /dev/null
	1>&2
	(
	trap "" SIGHUP

while :
do
	if [ ! -f /$QQEDIR/RequestsNum ];then
		echo "Possible loss of your last request, file RequestsNum was deleted."
		cnt=0
		echo $cnt >"/$QQEDIR/RequestsNum"	
	else
		read cnt < /$QQEDIR/RequestsNum	
	fi
	
	if [ ! $cnt = 0 ];then
		if [ ! -d /$QQEDIR ]; then
			mkdir /$QQEDIR
		fi
		for (( i=0;i<$cnt;i++ )); do
			if [ -f /$QQEDIR/REFERRER$((i+1)) ];then
				read temp < /$QQEDIR/REFERRER$((i+1))
				rm /$QQEDIR/REFERRER$((i+1))
			else
				temp="none"
			fi
			read temp1 < /$QQEDIR/URL$((i+1))
			rm /$QQEDIR/URL$((i+1))	
			DaemonArray=( "${DaemonArray[@]}" "$temp" )
			DaemonArray=( "${DaemonArray[@]}" "$temp1" )
		done
	fi

	if [ $killed = 1 ];then
		if [ ! ${#array1[@]} = 0 ];then
			array1=( `cat "/$QQEDIR/.queue"`)
			Hype array1 DaemonArray
		fi
	fi	


	
	if [ ! ${DaemonArray[1]} = "" ];then
		echo "Downloading:\nReferrer - ${DaemonArray[0]} Url - ${DaemonArray[1]}\n" >>/$QUEUE/.status
		echo "${DaemonArray[0]} ${DaemonArray[1]} " >>/$QUEUE/.queue
		echo "To download:\n" >>/$QUEUE/.status
		for (( i=2;i<${#DaemonArray[@]};i=j ));do
			((j=i+1))
			echo "Referrer - ${DaemonArray[${i}]} Url - ${DaemonArray[${j}]}" >>/$QUEUE/.status
			echo "${DaemonArray[${i}]} ${DaemonArray[${j}]} " >>/$QUEUE/.queue
			((j=i+2))
		done

		if [ "${DaemonArray[0]}" = "none" ]; then
			`$GETELEMFUNC -c -q -P "/Downloads/fetched4you/${DaemonArray[1]}" ${DaemonArray[1]}`
			echo "`date +%s`  ${DaemonArray[1]}" >>/$QQEDIR/.finished 
		else
			`$GETELEMFUNC -c -q -P "/Downloads/fetched4you/${DaemonArray[0]}/${DaemonArray[1]}" ${DaemonArray[1]}`
			echo "`date +%s` ${DaemonArray[0]} ${DaemonArray[1]}" >>/$QQEDIR/.finished 
		fi
		
		temp3=${#DaemonArray[@]} 
		((temp3=temp3-1))
		echo "temp3=$temp3"
		declare -a DaemonArrayNew=( ${DaemonArray[@]:2:$temp3} )
		declare -a DaemonArray=( ${DaemonArrayNew[@]:0:$temp3} )

		echo 0 > "/$QQEDIR/RequestsNum"	
	fi
	sleep 3
done
) &
PIDNUM=$!
echo $PIDNUM > /$QQEDIR/Daemon
disown -h $PIDNUM

}

####

if [ "$1" = "-w" ]; then
	QQEDIR=$2
	STARTARG=2
	if [ "$2" = "-r" ]; then
		echo "Incorrect request fetch4me -w -r." 1>&2
		exit 1
	fi
	
	if [ "$2" = "-w" ]; then
		echo "Incorrect request fetch4me -w -w." 1>&2
		exit 1
	fi
	
	if [ "$3" = "-r" ]; then
		REFERRER=$4
		REFEXISTS=1
		STARTARG=4
	fi
 elif [ "$1" = "-r" ]; then
	REFERRER=$2
	REFEXISTS=1
	STARTARG=2	
	if [ "$2" = "-w" ]; then
		echo "Incorrect request fetch4me -r -w." 1>&2
		exit 1
	fi
	
	if [ "$2" = "-r" ]; then		
		echo "Incorrect request fetch4me -r -r." 1>&2
		exit 1
	fi
		
	if [ $# -le "2" ]; then
		echo "Incorrect request. No URLs." 1>&2
		exit 1
	fi
	
	if [ $3 = "-w" ]; then
		if [ $3 -le "5" ]; then
			echo "Incorrect request. No URLs." 1>&2
			exit 1
		fi
		QQEDIR=$4
		STARTARG=4
	fi
fi
 	
if [ -z "$QQEDIR" ]; then
	QQEDIR="/.fetch4me"
fi

if [ -z "$GETELEMFUNC" ]; then
	GETELEMFUNC="wget"
fi

if [ $# -le "2" -a "$REFEXISTS" = "1" ]; then
	echo "Incorrect request. No URLs." 1>&2
	exit 1
fi


ARGS=("$@")
if [[ -f $QQEDIR/RequestsNum ]];then
	read rqstNum < $QQEDIR/RequestsNum	
else
	rqstNum=0
fi

urlNum=0
if [[ ! -d $QQEDIR ]];then 
	mkdir /$QQEDIR
fi

for (( i=$STARTARG; i<${#ARGS[@]}; i++)); do
	if [ "${ARGS[${i}]}" = "-w" ]; then	
		echo "Incorrect request. -w in a wrong place." 1>&2
		exit 1
	fi	
		
	if [ "${ARGS[${i}]}" = "-r" ]; then
		((j=i+1))
		if [ "${ARGS[${j}]}" = "-r" ]; then
			echo "Incorrect request. -r -r." 1>&2
			exit 1
		fi

		if [ "${ARGS[${j}]}" = "-w" ]; then
			echo "Incorrect request. -w in a wrong place." 1>&2
			exit 1
		fi

		if [ $j -lt ${#ARGS[@]} ];then	
			REFERRER=${ARGS[${j}]}
			REFEXISTS=1
			((i=i+1))	
		else 
			echo "Incorrect request. Not enough arguments for -r." 1>&2
			exit 1
		fi
	fi

	((rqstNum=$rqstNum+1))
	((urlNum=$urlNum+1))
	ARRAY[$urlNum]=${ARGS[${i}]}
	
done

for (( i=1;i<=$urlNum;i++ )); do
	echo $(($rqstNum-$urlNum+$i)) > "/$QQEDIR/RequestsNum"	
	if [ ! "$REFERRER" = "" ]; then
		echo $REFERRER > "/$QQEDIR/REFERRER$(($rqstNum-$urlNum+$i))"
	fi
	echo ${ARRAY[${i}]} > "/$QQEDIR/URL$(($rqstNum-$urlNum+$i))"		
done

if [  -f /$QQEDIR/Daemon ];then 
	read PIDNUM < /$QQEDIR/Daemon
	if  ! `ps -A |grep ${PIDNUM}|grep fetch4me >> /dev/null` 
	then
		killed=1
		startDaemon
	fi
else
	touch /$QQEDIR/Daemon
	touch /$QQEDIR/.queue
	touch /$QQEDIR/.status
	touch /$QQEDIR/.finished
	startDaemon
fi





